name: RUNNING CI [BUILD AND TEST] 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup vera 
      run: sh /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/scripts/github/VeraSetup.sh
    - name: Style-Checking
      run: make style-check

  avr-build:
    runs-on: ubuntu-latest
    needs: [style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building CPP Version For Target AVR
      run: sh /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/scripts/github/AvrCompilerSetup.sh
    - name: Building CPP Version For Target AVR
      run: make build-avr
    - name: Upload objects artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects-artifact
        path: /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/.build/obj

  regression-test:
    runs-on: ubuntu-latest
    needs: [avr-build]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Test Build
      run: sh /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/scripts/github/AvrCompilerSetup.sh
    - name: Download objects artifact
      uses: actions/download-artifact@v2
      with:
        name: objects-artifact
        path: /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/.build/obj
    - name: Configure Tests
      run: sh /home/runner/work/cpp_mcu_interface/cpp_mcu_interface/scripts/github/SimulavrSetup.sh
    - name: Run Regressions
      run: make run-regressions filter=all
    
  Clean:
    runs-on: ubuntu-latest
    needs: [regression-test]
    steps:
    - uses: actions/checkout@v3
    - name: Cleaning 
      run: make clean